Blogsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import blogger.views

urlpatterns = [
	url(r'^$', blogger.views.IndexView.as_view()),
	url(r'^blogger/', include('blogger.urls')),
    # url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/', blogger.views.LoginView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

blogger/urls.py
from django.conf.urls import url
from . import views

app_name = 'blogger'

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^login$', views.LoginView.as_view(), name='login'),
	url(r'^signup$', views.SignupView.as_view(), name='signup'),
	url(r'^blog/([a-zA-Z0-9_]+)$', views.BlogView.as_view(), name='blog'),
	url(r'^blog/([a-zA-Z0-9_]+)/([0-9]+)/(.+)$', views.BlogPostView.as_view(), name='blogpost'),
	url(r'^blogmanager$', views.BlogManagerView.as_view(), name='blogmanager'),
	url(r'^accountmanager$', views.AccountManagerView.as_view(), name='accountmanager'),
	url(r'^blogpostcreate$', views.BlogPostCreateView.as_view(), name='blogpostcreate'),
	url(r'^blogpostedit/(?P<blogpost_id>[0-9]+)$', views.BlogPostEditView.as_view(), name='blogpostedit'),
	url(r'^blogpostcomment/([a-zA-Z0-9_]+)/([0-9]+)/(.+)$', views.addBlogPostComment, name='blogpostcomment'),
	url(r'^logout$', views.logoutView, name='logout'),
	url(r'^error$', views.ErrorView.as_view(), name='error'),
	
]

blogger/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.

class Blog(models.Model):
	blog_title = models.CharField(max_length=100, primary_key=True)
	pub_date = models.DateTimeField('date published')
	blog_description = models.CharField(max_length=300, null=True)
	blog_banner = models.ImageField(upload_to='images/%Y/%m/%d', null=True)
	blog_background_color = models.CharField(max_length=30, null=True)
	user = models.OneToOneField(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.blog_title

class BlogPost(models.Model):
	blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
	blogpost_title = models.CharField(max_length=200)
	blogpost_text = models.CharField(max_length=100000)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.blogpost_title

class ImageDoc(models.Model):
	image = models.ImageField(upload_to='images/%Y/%m/%d')
	blogpost = models.ForeignKey(BlogPost, on_delete=models.CASCADE)

class BlogPostComment(models.Model):
	blogpost = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
	commenter = models.CharField(max_length=100)
	comment_content = models.CharField(max_length=1000)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.commenter

blogger/forms.py
from django import forms
from django.core import validators

# attributes are declared in the forms, which gives a weird mixing of responsibilities for this file
# there is a better way but requires the download of django-widget-tweaks which separates responsibilities

class SignupForm(forms.Form):
	username = forms.CharField(label='Username', max_length=25, widget=forms.TextInput(attrs={'class': 'form-control'}))
	password = forms.CharField(label='Password', max_length=25, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
	# need to add in validation here
	blog_title = forms.CharField(label='Blog Title', max_length=50, validators=[validators.validate_slug], widget=forms.TextInput(attrs={'class': 'form-control'}))

class LoginForm(forms.Form):
	username = forms.CharField(label='Username', max_length=25, widget=forms.TextInput(attrs={'class': 'form-control'}))
	password = forms.CharField(label='Password', max_length=25, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class BlogPostForm(forms.Form):
	blogpost_title = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Post Title'}))
	blogpost_text = forms.CharField(label='', widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Content'}))
	image = forms.ImageField(label='Image', required=False)

class CommentForm(forms.Form):
	comment = forms.CharField(label='', widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write a comment'}))
	commenter = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}), required=False)
	prev_url = forms.CharField(widget=forms.HiddenInput())

class BlogEditForm(forms.Form):
	blog_description = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Blog Description'}), required=False)
	blog_background_color = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Background Color (e.g. red/green/#fff/#123456)'}), required=False)
	blog_banner = forms.ImageField(label='Banner Image', required=False)

blogger/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import UserPassesTestMixin
from django import forms
from django.urls import reverse
from django.db.models import F
from django.views import generic, View
from django.utils import timezone
from dateutil.relativedelta import relativedelta
from .models import *
from .forms import *
from collections import OrderedDict
import datetime

PREVIEW_TEXT_CHAR = 1000;

def can_access(user, blogpost_id):
	blogpost = get_object_or_404(BlogPost, pk=blogpost_id)
	blog = blogpost.blog
	if user != blog.user:
		return False
	else:
		return True

class IndexView(View):
	def get(self, request):
		return render(request, 'blogger/index.html')

class LoginView(View):
	def get(self, request):
		form = LoginForm()
		return render(request, 'blogger/login.html', {'form': form})
	def post(self, request):
		form = LoginForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			try:
				user = User.objects.get(username__iexact=username)
				if user.check_password(password):
					login(request, user)
					return HttpResponseRedirect(reverse('blogger:blogmanager'))
				else:
					return render(request, 'blogger/login.html', {'error_message': 'Unable to log you in.', 'form': form})
			except User.DoesNotExist:
				return render(request, 'blogger/login.html', {'error_message': 'Unable to log you in.', 'form': form})
		return render(request, 'blogger/login.html', {'form': form})

class SignupView(View):
	def get(self, request):
		form = SignupForm()
		return render(request, 'blogger/signup.html', {'form': form})
	def post(self,request):
		# add some checks to ensure fields are filled up
		form = SignupForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			email = form.cleaned_data['email']
			blog_title = form.cleaned_data['blog_title']
			if Blog.objects.filter(blog_title__iexact=blog_title).exists():
				return render(request, 'blogger/signup.html', {'error_message': 'Blog title already exists', 'form': form})
			elif User.objects.filter(username__iexact=username).exists():
				return render(request, 'blogger/signup.html', {'error_message': 'Username already exists', 'form': form})
			else:
				user = User.objects.create_user(username, email, password)
				user.save()
				login(request, user)
				blog = Blog(blog_title=blog_title, pub_date=timezone.now(), user=request.user)
				blog.save()
			return HttpResponseRedirect(reverse('blogger:blogmanager'))
		return render(request, 'blogger/signup.html', {'form': form})

class BlogView(View):
	def get(self, request, blog_title):
		blog = get_object_or_404(Blog, pk__iexact=blog_title)
		blogposts = blog.blogpost_set.all().order_by('-pub_date')
		context = {
			'blog': blog,
			'blogposts': [],
			'dates': [],
		}
		dates = []
		for blogpost in blogposts:
			image_count = blogpost.imagedoc_set.all().count()
			if image_count>0:
				context['blogposts'].append((blogpost,blogpost.imagedoc_set.all()[image_count-1], blogpost.blogpost_text[:PREVIEW_TEXT_CHAR]))
			else:
				context['blogposts'].append((blogpost, '', blogpost.blogpost_text[:PREVIEW_TEXT_CHAR]))
			dates.append(timezone.localtime(blogpost.pub_date))
		dates = [(date.strftime('%B'),date.year) for date in dates]
		context['dates'] = list(OrderedDict.fromkeys(dates))
		if self.request.user.is_authenticated():
			context['username'] = request.user.username
		return render(request, 'blogger/blog.html', context)

	def post(self, request, blog_title):
		blog = get_object_or_404(Blog, pk__iexact=blog_title)
		context = {
			'username': request.user.username,
			'blog': blog,
			'blogposts': [],
			'dates': [],
		}
		dates = []
		if 'datefilter' in request.POST:
			datetime = request.POST['datefilter']
			if datetime == 'All Time':
				blogposts = blog.blogpost_set.all().order_by('-pub_date')
			else:
				datetime = datetime.split(' ')
				month = convertMonthNameToNumber(datetime[0])
				year = datetime[1]
				blogposts = blog.blogpost_set.all().order_by('-pub_date').filter(pub_date__month=month, pub_date__year=year)
		for blogpost in blogposts:
			image_count = blogpost.imagedoc_set.all().count()
			if image_count>0:
				context['blogposts'].append((blogpost,blogpost.imagedoc_set.all()[image_count-1], blogpost.blogpost_text[:PREVIEW_TEXT_CHAR]))
			else:
				context['blogposts'].append((blogpost, '', blogpost.blogpost_text[:PREVIEW_TEXT_CHAR]))

		blogposts = blog.blogpost_set.all().order_by('-pub_date')
		dates = [timezone.localtime(blogpost.pub_date) for blogpost in blogposts]
		dates = [(date.strftime('%B'),date.year) for date in dates]
		context['dates'] = list(OrderedDict.fromkeys(dates))

		return render(request, 'blogger/blog.html', context)

class BlogPostView(View):
	def get(self, request, blog_title, blogpost_id, blogpost_title):
		blog = get_object_or_404(Blog, pk=blog_title)
		blogpost = get_object_or_404(BlogPost, pk=blogpost_id)
		comment_form = CommentForm(initial={'prev_url': 'blogpost'})
		comments = blogpost.blogpostcomment_set.all().order_by('pub_date')
		if blogpost.blog != blog or blogpost.blogpost_title != blogpost_title:
			return render(request, 'blogger/error.html')
		context = {
			'blog': blog,
			'blogpost': blogpost,
			'comment_form': comment_form,
			'comments': comments,
		}
		image_count = blogpost.imagedoc_set.all().count()
		if image_count>0:
			context['image'] = blogpost.imagedoc_set.all()[image_count-1]
		return render(request, 'blogger/blogpost.html', context)

@method_decorator(login_required, name='get')
@method_decorator(login_required, name='post')
class BlogManagerView(View):
	def get(self, request):
		blog = get_object_or_404(Blog, user=request.user)
		blogposts = blog.blogpost_set.all().order_by('-pub_date')
		context = {
			'username': request.user.username,
			'blog': blog,
			'blogposts': [],
			'dates': []
		}
		dates = []
		for blogpost in blogposts:
			image_count = blogpost.imagedoc_set.all().count()
			if image_count>0:
				context['blogposts'].append((blogpost,blogpost.imagedoc_set.all()[image_count-1], blogpost.blogpost_text[:PREVIEW_TEXT_CHAR]))
			else:
				context['blogposts'].append((blogpost, '', blogpost.blogpost_text[:PREVIEW_TEXT_CHAR]))
			dates.append(timezone.localtime(blogpost.pub_date))
		dates = [(date.strftime('%B'),date.year) for date in dates]
		context['dates'] = list(OrderedDict.fromkeys(dates))
		return render(request, 'blogger/blogmanager.html', context)
	def post(self, request):
		blog = get_object_or_404(Blog, user=request.user)
		context = {
			'username': request.user.username,
			'blog': blog,
			'blogposts': [],
			'dates': [],
		}
		dates = []
		if 'datefilter' in request.POST:
			datetime = request.POST['datefilter']
			if datetime == 'All Time':
				blogposts = blog.blogpost_set.all().order_by('-pub_date')
			else:
				datetime = datetime.split(' ')
				month = convertMonthNameToNumber(datetime[0])
				year = datetime[1]
				blogposts = blog.blogpost_set.all().order_by('-pub_date').filter(pub_date__month=month, pub_date__year=year)
		for blogpost in blogposts:
			image_count = blogpost.imagedoc_set.all().count()
			if image_count>0:
				context['blogposts'].append((blogpost,blogpost.imagedoc_set.all()[image_count-1], blogpost.blogpost_text[:PREVIEW_TEXT_CHAR]))
			else:
				context['blogposts'].append((blogpost, '', blogpost.blogpost_text[:PREVIEW_TEXT_CHAR]))

		blogposts = blog.blogpost_set.all().order_by('-pub_date')
		dates = [timezone.localtime(blogpost.pub_date) for blogpost in blogposts]
		dates = [(date.strftime('%B'),date.year) for date in dates]
		context['dates'] = list(OrderedDict.fromkeys(dates))

		return render(request, 'blogger/blogmanager.html', context)

@method_decorator(login_required, name='get')
@method_decorator(login_required, name='post')
class AccountManagerView(View):
	def get(self, request):
		blog = get_object_or_404(Blog, user=request.user)
		form_content = {
			'blog_description': blog.blog_description,
			'blog_background_color': blog.blog_background_color,
		}
		form = BlogEditForm(form_content)
		context = {
			'username': request.user.username,
			'blog': blog,
			'form': form,
		}
		return render(request, 'blogger/accountmanager.html', context)
	def post(self, request):
		user = request.user
		form = BlogEditForm(request.POST, request.FILES)
		blog = get_object_or_404(Blog, user=request.user)
		if form.is_valid():
			if 'delete' in request.POST:
				logout(request)
				user.delete()
				return HttpResponseRedirect(reverse('blogger:index'))
			
			blog.blog_description = form.cleaned_data['blog_description']
			blog.blog_background_color = form.cleaned_data['blog_background_color']
			if request.FILES.get('blog_banner'):
				blog.blog_banner = form.cleaned_data['blog_banner']
			blog.save()
		return HttpResponseRedirect(reverse('blogger:blogmanager'))

@method_decorator(login_required, name='get')
@method_decorator(login_required, name='post')
class BlogPostCreateView(View):
	def get(self, request):
		form = BlogPostForm()
		blog = get_object_or_404(Blog, user=request.user)
		context = {
			'username': request.user.username,
			'form': form,
			'blog': blog,
		}
		return render(request, 'blogger/blogpostmanager.html', context)

	def post(self, request):
		form = BlogPostForm(request.POST, request.FILES)
		blog = get_object_or_404(Blog, user=request.user)
		context = {
			'username': request.user.username,
			'form': form,
			'blog': blog,
		}
		if form.is_valid():
			blog = get_object_or_404(Blog, user=request.user)

blogger/templates/blogger/blog.html
{% include "./maintemplateheader.html" %}
{% load static %}
{% include "./blogtemplate.html" %}

<div class="container">
<div class="row">
<div class="col-md-12">
<hr>
<div class="row">
		<div class="col-md-9">
		{% if blogposts %}
			{% for blogpost,image,blogpost_text in blogposts %}
			<h2>{{ blogpost.blogpost_title|linebreaksbr }}</h2>
			<small>&nbsp&nbsp&nbsp{{blogpost.pub_date}}</small>
			<div class="panel panel-default blogpost">	
				<div class="panel-body">
					{% if image %}
					<div class="col-md-3">
					<img src="{{ image.image.url }}">
					</div>
					<div class="col-md-9">
					<p class="wordwrap">
					{{blogpost_text|linebreaksbr}}
					</p>
					</div>
					{% else %}
					<div class="col-md-12">
					<p class="wordwrap">
					{{blogpost_text|linebreaksbr}}
					</p>
					</div>
					{% endif %}
				</div>
				<div class="panel-body">
				<a href="{% url 'blogger:blogpost' blog.blog_title blogpost.id blogpost.blogpost_title %}">
				<button type="button" class="btn btn-default pull-right">Read More </button>
				</a>
				
				</div>
			</div>
			{% endfor %}
		{% else %}
		<h4>No Posts Yet!</h4>
		{% endif %}
		</div>

		<div class="col-md-3">
		<h3>Filters</h3>
			<div class="panel panel-info">
			<div class="panel-heading">
			Posts From
			</div>
			<div class="panel-body">
			<form action="{% url 'blogger:blog' blog.blog_title %}" method="POST">
			{% csrf_token %}
			<input type="submit" name="datefilter" value="All Time" style="background:none; border-width:0px; color:blue;"/>
			<br/>
			{% for month,year in dates %}
			<input type="submit" name="datefilter" value="{{ month }} {{ year }}" style="background:none; border-width:0px; color:blue;"/>
			<br/>
			{% endfor %}
			</form>
			</div>
			</div>
		</div>
	</div>

	</div>
	</div>
	</div>
	<br/>
	{% include "./jstemplate.html" %}

blogger/templates/blogger/blogmanager.html
{% include "./maintemplateheader.html" %}
{% load static %}
<div class="container padded"></div>

<div class="container">
<div class="row">
<div class="col-md-10 col-md-offset-1">
	
	<div class="container-fluid">
	<div class="row">
		<div class="page-header">
	    	<h1 class="text-center">Blog Manager</h1>
		</div>	
	</div>
	</div>
	<div class="blogmanager">
	<br>
	<div class="container-fluid">
	<div class="row">
		<div class="col-md-9">
		{% if blogposts %}
			{% for blogpost,image,blogpost_text in blogposts %}
			<div class="panel panel-default blogpost">
				<div class="panel-heading">
				
				<h4 class="panel-title">{{ blogpost.blogpost_title|linebreaksbr }}</h4>
				</div>
				<div class="panel-body">
					{% if image %}
					<div class="col-md-4">
					<img src="{{ image.image.url }}">
					</div>
					<div class="col-md-8">
					<p class="wordwrap">
					{{blogpost_text|linebreaksbr}}
					</p>
					</div>
					{% else %}
					<div class="col-md-12">
					<p class="wordwrap">
					{{blogpost_text|linebreaksbr}}
					</p>
					</div>
					{% endif %}
				</div>
				<div class="panel-body">
				<div class="btn-group btn-group-xs pull-right" role="group">
				<a href="{% url 'blogger:blogpostedit' blogpost.id %}">
				<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span>&nbsp  {{blogpost.blogpostcomment_set.all.count}}  comments</button>
				<button type="button" class="btn btn-default">Edit</button>
				</a>
				</div>
				<small>{{blogpost.pub_date}}</small>
				</div>
			</div>
			{% endfor %}
		{% else %}
		<div class="panel panel-default blogpost">
		<div class="panel-body">
		No posts yet!
		</div>
		</div>
		{% endif %}
		</div>

		<div class="col-md-3">
			<a href="{% url 'blogger:blog' blog.blog_title %}">
			<button type="button" class="btn  btn-default btn-block">Check out your blog!</button>
			</a>
			<a href="{% url 'blogger:blogpostcreate' %}">
			<button type="button" class="btn  btn-default btn-block">Create a new post</button>
			</a>
			<a href="{% url 'blogger:accountmanager' %}">
			<button type="button" class="btn  btn-default btn-block">Go to your account</button>
			</a>

			<br>
			<div class="panel panel-primary">
			<div class="panel-heading">
			Posts From
			</div>
			<div class="panel-body">
			<form action="{% url 'blogger:blogmanager' %}" method="POST">
			{% csrf_token %}
			<input type="submit" name="datefilter" value="All Time" style="background:none; border-width:0px; color:blue;"/>
			<br/>
			{% for month,year in dates %}
			<input type="submit" name="datefilter" value="{{ month }} {{ year }}" style="background:none; border-width:0px; color:blue;"/>
			<br/>
			{% endfor %}
			</form>
			</div>
			</div>
		</div>
	</div>
	</div>
	<br/>
	</div>
</div>
</div>
</div>
<br/>
{% include "./jstemplate.html" %}

blogger/templates/blogger/blogpost.html
{% include "./maintemplateheader.html" %}
{% load static %}
{% include "./blogtemplate.html" %}

<div class="container">
<div class="row">
<div class="col-md-12">
<hr>
<a href="{% url 'blogger:blog' blog.blog_title %}">
<button type="button" class="btn btn-primary pull-right">Back to the blog</button></a>
<h1>{{ blogpost.blogpost_title|linebreaksbr }}</h1>
<small>&nbsp&nbsp&nbsp{{blogpost.pub_date}}</small>

<div class="panel panel-default">	
<div class="panel-body">

	<div class="col-md-12">
	<p class="wordwrap">
	{{blogpost.blogpost_text|linebreaksbr}}
	</p>
	</div>
	{% if image %}
	<div class="col-md-10 col-md-offset-1">
	<p class="text-center">
	<img src="{{ image.image.url }}">
	</p>
	</div>
	{% endif %}
</div>
</div>
<br/>
<hr>

<!-- <p>{{ blogpost.blogpost_title }}</a></p>
<p>{{ blogpost.blogpost_text }}</p>
<p>{{ blogpost.pub_date }}</p>
{% if image %}
	<img src="{{ image.image.url }}">
{% endif %} -->

{% include "./commentstemplate.html" %}

<br/>
<form action="{% url 'blogger:blogpostcomment' blogpost.blog.blog_title blogpost.id blogpost.blogpost_title%}" method="post">
{% csrf_token %}
{{ comment_form.as_p }}
<br/>
<button class="btn btn-primary btn-lg" type="submit" value="submit">Submit Comment
</button>
</form>

</div>
</div>
</div>
<br/>
{% include "./jstemplate.html" %}

blogger/templates/blogger/blogpostmanager.html
{% include "./maintemplateheader.html" %}
{% load static %}
<div class="container padded"></div>

<div class="container">
<div class="row">
<div class="col-md-10 col-md-offset-1">
	
	<div class="container-fluid">
	<div class="row">
		<div class="page-header">
	    	<h1 class="text-center">
	    	{% if blogpost %}
	    	Edit Post
	    	{% else %}
	    	Create Post
	    	{% endif %}
	    	</h1>
		</div>	
	</div>
	</div>

{% if blogpost %}
	<form action="{% url 'blogger:blogpostedit' blogpost.id %}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	
	{{ form.as_p }}
	{% if image %}
	<p>Saved Image</p>
	<img src="{{ image.image.url }}">
	<br/>
	{% endif %}
	<br/>
	<button class="btn btn-primary btn-lg" type="submit" value="submit">Save Post
	</button>
	&nbsp
	<button class="btn btn-danger btn-lg" name="delete" type="submit" value="Delete Post">Delete Post
	</button>
<!-- 	<input type="submit" name='delete' value="Delete Post"> -->
	</form>

	<br/><br/><br/>

	{% include "./commentstemplate.html" %}

	<br/>
	<form action="{% url 'blogger:blogpostcomment' blogpost.blog.blog_title blogpost.id blogpost.blogpost_title%}" method="post">
	{% csrf_token %}
	{{ comment_form.as_p }}
	<br/>
	<button class="btn btn-primary btn-lg" type="submit" value="submit">Submit Comment
	</button>
	</form>
	<br/>
	<a href="{% url 'blogger:blogmanager' %}">Back to blog manager</a>


{% else %}

	<form action="{% url 'blogger:blogpostcreate' %}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}

	<button class="btn btn-primary btn-lg" type="submit" value="submit">Submit
	</button>
	
	</form>

	<br/>
	<a href="{% url 'blogger:blogmanager' %}">Back to blog manager</a>

{% endif %}
</div>
</div>
</div>
<br/>
{% include "./jstemplate.html" %}

blogger/templates/blogger/maintemplateheader.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    {% if blog %}
    <title>{{ blog.blog_title }}</title>
    {% else %}
    <title>Seetohblog - Lightweight Blogger</title>
    {% endif %}
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'blogger/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'blogger/css/landing-page.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'blogger/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <link rel="stylesheet" type="text/css" href="{% static 'blogger/css/main.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="{% url 'blogger:index' %}">Seetoh Blog</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    {% if not blog %}
                    <li>
                        <a href="{% url 'blogger:index' %}#about">About</a>
                    </li>
                    <li>
                        <a href="{% url 'blogger:index' %}#contact">Contact</a>
                    </li>
                    {% endif %}
                    {% if request.user.username %}
                    <li>
                    	<a href="{% url 'blogger:blogmanager' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp&nbsp{{request.user.username}}</a>
                	</li>
                	<li>
                		<a href="{% url 'blogger:logout' %}">Logout</a>
            		</li>	
                    {% else %}	
                    <li>
                        <a href="{% url 'blogger:login' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'blogger:signup' %}">Signup</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>